name: iconsax
description: Iconsax for flutter (1000+ icons 6 diferent styles, total 6000+ icons).
version: 0.0.9
homepage: https://iconsax.io/
repository: https://github.com/luisDanielRoviraContreras/flutter_iconsax
issue_tracker: https://github.com/luisDanielRoviraContreras/flutter_iconsax/issues
documentation: https://github.com/luisDanielRoviraContreras/flutter_iconsax


environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    -  fonts/iconsax.ttf
    
  fonts:
    - family: iconsax
      fonts:
        - asset: fonts/iconsax.ttf
      